### ISSUE TITLE
Add Purse to Redis documentation?

### ISSUE THREAD

**Issue by brainix** [plataux/purse#1]
Hi there! 👋🏾 

I'm the author of [Pottery](https://github.com/brainix/pottery), and Purse looks brilliant! I've never done asyncio programming before, but I'm learning from reading Purse's clean source code!

I had a thought... How would you feel about adding Purse to the official Redis documentation? You might get some additional interest, users, and even contributors. The Redis docs maintainers allowed me to add Pottery, so I'm sure they'd be happy to include Purse:
1. [Redis clients](https://redis.io/clients#python)
2. [Redlock](https://redis.io/topics/distlock)

You could open a Pull Request to add Purse to the [Redis clients](https://github.com/redis/redis-doc/blob/de426bd3c6cda194e91387bb188285a05d9553b4/clients.json#L1591-L1598) and [Redlock](https://github.com/redis/redis-doc/blob/2c1955babf3a59bd7f434986987e67d92452101b/topics/distlock.md?plain=1#L28) pages. Or if you'd prefer, with your permission, I'd be happy to open the Pull Request against the Redis docs.

Either way, it's your call if you want to add Purse to the Redis docs. Thank you, and keep up the great work! 🚀 
Raj

**Comment by mk-mahfouz** [comment]
Hey Thank you so much for the kind words, it is great to hear from you!

That is a great idea, I think it will benefit many people starting new projects, and it will hopefully bring in creative contributions as well.

I am currently working on some detailed documentation based on recent project experiences, tips and tricks, etc.

Do you think that stabilizing the API and publishing on pypi needs to happen before inclusion in Redis docs? Or do you think it doesn't matter that much? If so, I will review how you had setup pottery for pypi and see how to get this done.

Also, I would greatly appreciate your help opening the pull request, as you bring in credibility and experience to the table.

Thank you so much, and Happy new Year!!

**Comment by peedrr** [comment]
Hey @plataux, I just found out about Purse after @brainix [pointed it out](https://github.com/brainix/pottery/issues/453#issuecomment-1003286306). And I only found out about Pottery after seeing it listed in the Redis docs. (I loved the concept of Pottery and was sad that it didn't support asyncio or Sorted Sets, hence my excitement about Purse - keep on keeping on!)

My 2¢ is that Purse should already be listed on Redis's docs. If you welcome contributions at this early stage then I think this would be a good way to raise awareness and encourage participation. From my own experience of searching for a client library, and considering the fast pace of Redis's own development, I value _active development_ and _clean code_ more than stability.

I also wanted to point out, if you hadn't already noticed, that [Redis actively encourage PRs](https://redis.io/clients) in order to get client libraries listed in their docs and so I'm not sure brainix's considerable credibility is necessary in this instance. (Although perhaps @brainix might consider encouraging Redis to prune the list of stale client projects, or somehow add a 'last updated' column... the current list is long and largely made up of abandoned projects!)

**Comment by mk-mahfouz** [comment]
Hey @peedrr,

You are right, and I'm glad to learn about your enthusiasm about this.

I do agree that putting it out there will potentially help others in their own projects, and opening it up for contributions, ideas and feedback will surely be helpful to the project in general.

One other reason I was putting this on the back burner is because I made some very opinionated design choices, for instance.

```python
value = await purse_dict.get("new_key")
```
Doesn't raise a ``KeyError``, but rather returns ``None`` when the key is absent, to promote minimal networking. Such decisions take some time to digest and to be tested in a real applications to conclude their correctness.

In any case, I will take steps to update the docs with latest features, and will issue a PR to the Redis docs repo.

Thanks Again.
